---
- hosts: localhost
  gather_facts: True
  vars:
    prefix: 'cm'
    aws_region: 'ap-southeast-2'
# Acceptable values are 'prod' or 'nonprod'    
    env: 'nonprod'
  roles:
    - vpc_core
# remove the comment marker from the lines below to add extra features    
    - database


