---
AWSTemplateFormatVersion: '2010-09-09'
Description: RDS Subnet Group

Parameters:
  subnetStackName:
    Type: String

  name:
    Type: String

Resources:
  subnetGroup:
    Type: AWS::RDS::DBSubnetGroup
    Properties:
      DBSubnetGroupDescription: 'RDS Subnet Group'
      SubnetIds:
        - Fn::ImportValue: !Sub '${subnetStackName}-subnetRestrictedA'
        - Fn::ImportValue: !Sub '${subnetStackName}-subnetRestrictedB'
        - Fn::ImportValue: !Sub '${subnetStackName}-subnetRestrictedC'
      Tags:
        -
          Key: Name
          Value: !Sub ${name} Database Subnet Group
Outputs:
  subnetGroup:
    Value: !Ref subnetGroup
    Export:
      Name: !Sub '${AWS::StackName}-subnetGroup'
