---
AWSTemplateFormatVersion: '2010-09-09'

#
# This template creates an NAT Gateway for the specified VPC
#

Description: Create NAT Gateway

Parameters:
  name:
    Type: String

  vpcStackName:
    Type: String
    Description: Name of the CFN Stack which creates the VPC

  subnetStackName:
    Type: String
    Description: Name of the CFN Stack which creates the VPC

Resources:
  natEIPA:
    Type: AWS::EC2::EIP
    Properties:
      Domain: vpc

  natGatewayA:
    Type: AWS::EC2::NatGateway
    Properties:
      AllocationId:
        !GetAtt [ natEIPA, AllocationId ]
      SubnetId:
        Fn::ImportValue: !Sub '${subnetStackName}-subnetPublicA'
      Tags:
        - Key: Name
          Value: !Ref name

Outputs:
  gatewayId:
    Description: Internet Gateway ID
    Value: !Ref natGatewayA
    Export:
      Name: !Sub ${AWS::StackName}-gatewayId