---
- name: Create VPC Flow Logs
  cloudformation:
    stack_name: '{{ prefix }}-{{ env }}-vpc-flowlogs'
    state: 'present'
    region: '{{ aws_region }}'
    disable_rollback: False
    template: 'vpc_core/files/vpc-flowlog.yaml'
    template_parameters:
      name: '{{ prefix }}-{{ env }}'
      vpcStackName: '{{ prefix }}-{{ env }}-vpc'
