---
- name: Create VPC
  cloudformation:
    stack_name: '{{ prefix }}-{{ env }}-vpc'
    state: present
    region: '{{ aws_region }}'
    disable_rollback: False
    template: 'vpc_core/files/vpc-vpc.yaml'
    template_parameters:
      cidrBlock: '{{ vpc_cidr }}'
      name: '{{ prefix }}-{{ env }}'
