---
- name: Create Route53 Private Zone for the VPC
  cloudformation:
    stack_name: '{{ prefix }}-{{ env }}-vpc-route53'
    state: 'present'
    region: '{{ aws_region }}'
    disable_rollback: False
    template: 'vpc_core/files/vpc-route53.yaml'
    template_parameters:
      vpcStackName: '{{ prefix }}-{{ env }}-vpc'
      zoneName: '{{ prefix }}-{{ env }}.tld'
