---
- name: Create VPC NAT Gateway
  cloudformation:
    stack_name: '{{ prefix }}-{{ env }}-vpc-nat'
    state: 'present'
    region: '{{ aws_region }}'
    disable_rollback: False
    template: 'vpc_core/files/vpc-nat.yaml'
    template_parameters:
      name: '{{ prefix }}-{{ env }}'
      subnetStackName: '{{ prefix }}-{{ env }}-vpc-subnets'
      vpcStackName: '{{ prefix }}-{{ env }}-vpc'
