---
- name: Create VPC Endpoints
  cloudformation:
    stack_name: '{{ prefix }}-{{ env }}-vpc-endpoints'
    state: 'present'
    region: '{{ aws_region }}'
    disable_rollback: False
    template: 'vpc_core/files/vpc-endpoints.yaml'
    template_parameters:
      routeStackName: '{{ prefix }}-{{ env }}-vpc-routes'
      subnetStackName: '{{ prefix }}-{{ env }}-vpc-subnets'
      vpcStackName: '{{ prefix }}-{{ env }}-vpc'
